from enum import Enum

import numpy as np


ArrayDict = dict[str, np.ndarray]


class TaskType(Enum):
    BINARY_CLASSIFICATION = "binclass"
    MULTICLASS_CLASSIFICATION = "multiclass"
    REGRESSION = "regression"

    def __str__(self) -> str:
        """
        Return the string representation of the task type, which is the value of the enum.

        Returns:
            The string representation of the task type.
        """
        return self.value


class PredictionType(Enum):
    LOGITS = "logits"
    PROBS = "probs"


class DataSplit(Enum):
    TRAIN = "train"
    VALIDATION = "val"
    TEST = "test"


class DomainDataType(Enum):
    """Possible types of domain data."""

    CONTINUOUS = "continuous"
    DISCRETE = "discrete"


class ColumnType(Enum):
    """Possible types of column data."""

    NUMERICAL = "numerical"
    CATEGORICAL = "categorical"


class ComputerRepresentation(Enum):
    """Possible types of computer representation for data values."""

    FLOAT = "Float"


class IsTargetConditioned(Enum):
    """
    The condition on the y column.

    IsTargetConditioned.CONCAT: y is concatenated to X, the model learn a joint distribution of (y, X)
    IsTargetConditioned.EMBEDDING: y is not concatenated to X. During computations, y is embedded
        and added to the latent vector of X
    IsTargetConditioned.NONE: y column is completely ignored

    How does IsTargetConditioned affect the generation of y?
    IsTargetConditioned:
        IsTargetConditioned.CONCAT: the model synthesizes (y, X) directly, so y is just the first column
        IsTargetConditioned.EMBEDDING: y is first sampled using empirical distribution of y. The model only
            synthesizes X. When returning the generated data, we return the generated X
            and the sampled y. (y is sampled from empirical distribution, instead of being
            generated by the model)
            Note that in this way, y is still not independent of X, because the model has been
            adding the embedding of y to the latent vector of X during computations.
        IsTargetConditioned.NONE:
            y is synthesized using y's empirical distribution. X is generated by the model.
            In this case, y is completely independent of X.
    """

    CONCAT = "concat"
    EMBEDDING = "embedding"
    NONE = "none"


class Normalization(Enum):
    """Possible types of normalization."""

    STANDARD = "standard"
    QUANTILE = "quantile"
    MINMAX = "minmax"


class NumericalNaNPolicy(Enum):
    """Possible policies for dealng with NaNs in numerical data."""

    DROP_ROWS = "drop-rows"
    MEAN = "mean"


class CategoricalNaNPolicy(Enum):
    """Possible policies for dealng with NaNs in categorical data."""

    MOST_FREQUENT = "most_frequent"


class CategoricalEncoding(Enum):
    """Possible types of encoding for categorical data."""

    ONE_HOT = "one-hot"
    COUNTER = "counter"
    ORDINAL = "ordinal"


class TargetPolicy(Enum):
    """Possible types of policy for the model target."""

    DEFAULT = "default"


class TargetType(Enum):
    """Possible types of model target."""

    FLOAT = "float"
    LONG = "long"
