# Ensemble example configuration
# Base data directory (can be overridden from command line)
base_data_dir: examples/ensemble_attack/data
base_example_dir: examples/ensemble_attack

# Data paths (relative to base_data_dir)
data_paths:
  midst_data_path: ${base_data_dir}/midst_data_all_attacks # Used only for reading the data
  population_path: ${base_data_dir}/population_data  # Path where the population data should be stored
  processed_attack_data_path: ${base_data_dir}/attack_data # Path where the processed attack real train and evaluation data is stored
  attack_evaluation_result_path: ${base_example_dir}/attack_results # Path where the attack evaluation results will be stored

model_paths:
  metaclassifier_model_path: ${base_example_dir}/trained_models # Path where the trained metaclassifier model will be saved

# Pipeline control
pipeline:
  run_data_processing: true # Set this to false if you have already saved the processed data
  run_shadow_model_training: true # Set this to false if shadow models are already trained and saved
  run_metaclassifier_training: true


# Dataset specific information used for processing in this example
data_processing_config:
  population_attack_data_types_to_collect:
        [
          "tabddpm_black_box",
          "tabsyn_black_box",
          "tabddpm_white_box",
          "tabsyn_white_box",
          "clavaddpm_black_box",
          "clavaddpm_white_box",
        ]
  challenge_attack_data_types_to_collect:
        [
          "tabddpm_black_box",
        ]
  population_splits: ["train"]  # Data splits to be collected for population data
  challenge_splits: ["train"]  # Data splits to be collected for challenge points
  # The column name in the data to be used for stratified splitting.
  column_to_stratify: "trans_type"  # Attention: This value is not documented in the original codebase.
  folder_ranges:
    train: [[1, 31]]
    dev: [[51, 61], [91, 101]]
    final: [[61, 71], [101, 111]]
  # File names in MIDST data directories.
  single_table_train_data_file_name: "train_with_id.csv"
  multi_table_train_data_file_name: "trans.csv"
  challenge_data_file_name: "challenge_with_id.csv"
  population_sample_size: 40000 # Population size is the total data that your attack has access to.
  # The size of the master challenge dataset is half of the population size based on the attack design.
  # The other half is used for evaluation.
  # Original code: 40000

# Training and data settings for shadow models (temporary, numbers subject to change)
shadow_training:
  # Data Config files path used for training a TabDDPM model
  training_json_config_paths: # Config json files used for tabddpm training on the trans table
    table_domain_file_path: ${base_example_dir}/data_configs/trans_domain.json
    dataset_meta_file_path: ${base_example_dir}/data_configs/dataset_meta.json
    tabddpm_training_config_path: ${base_example_dir}/data_configs/trans.json
  # Model training artifacts are saved under shadow_models_data_path/workspace_name/exp_name
  # Also, training configs for each shadow model are created under shadow_models_data_path.
  shadow_models_output_path: ${base_data_dir}/shadow_models_and_data
  target_model_output_path: ${base_data_dir}/target_model_and_data
  final_shadow_models_path: [
          "${shadow_training.shadow_models_output_path}/initial_model_rmia_1/shadow_workspace/pre_trained_model/rmia_shadows.pkl",
          "${shadow_training.shadow_models_output_path}/initial_model_rmia_2/shadow_workspace/pre_trained_model/rmia_shadows.pkl",
          "${shadow_training.shadow_models_output_path}/shadow_model_rmia_third_set/shadow_workspace/trained_model/rmia_shadows_third_set.pkl",
      ] # Paths to final shadow models used for metaclassifier training (relative to shadow_models_output_path)
      # These paths are a result of running the shadow model training pipeline, specifically the
      # train_three_sets_of_shadow_models in shadow_model_training.py
      # Each .pkl file contains the training data, trained model and training results for all shadow models in a list.
  target_synthetic_data_path: ${shadow_training.target_model_output_path}/target_synthetic_data.csv
  # Path to final target model's synthetic data (relative to target_model_output_path)
  fine_tuning_config:
    fine_tune_diffusion_iterations: 200000 # Original code: 200000
    fine_tune_classifier_iterations: 20000 # Original code: 20000
    pre_train_data_size: 60000 # Original code: 60000
  number_of_points_to_synthesize: 20000 # Number of synthetic data samples to be generated by shadow models.
  # Original code: 20000


# Metaclassifier settings
metaclassifier:
  # Data types json file is used for xgboost model training.
  data_types_file_path: ${base_example_dir}/data_configs/data_types.json
  model_type: "xgb"
  # Model training parameters
  num_optuna_trials: 100 # Original code: 100
  num_kfolds: 5
  use_gpu: false
  # Temporary. Might remove having an epoch parameter.
  epochs: 1
  meta_classifier_model_name: ${metaclassifier.model_type}_metaclassifier_model


# General settings
random_seed: 42 # Set to null for no seed, or an integer for a fixed seed
