# Training example configuration
# Base data directory (can be overridden from command line)
base_data_dir: examples/gan/data
results_dir: examples/gan/results

ensemble_attack:
    random_seed: null  # Set this to a value if you want to set a random seed for reproducibility
    table_name: "trans"
    table_id_column_name: "trans_id"

    data_paths:
      processed_attack_data_path: ${base_data_dir}/ensemble_attack
      population_path: ${base_data_dir}/ensemble_attack
      attack_evaluation_result_path: ${results_dir}/evaluation_results # Path where the attack evaluation results will be stored

    data_processing_config:
      column_to_stratify: "trans_type"  # Attention: This value is not documented in the original codebase.
      population_sample_size: 40000 # Population size is the total data that your attack has access to.

    pipeline:
      #  TODO: properly test these
      run_data_processing: true # Set this to false if you have already saved the processed data
      run_shadow_model_training: true # Set this to false if shadow models are already trained and saved
      run_metaclassifier_training: true

    shadow_training:
      model_name: ctgan
      model_config:  # Configurations specific for the CTGAN model
        training:
          epochs: 300
          verbose: True
        synthesizing:
          sample_size: 20000
      shadow_models_output_path: ${results_dir}/ensemble_attack/shadow_models
      target_model_output_path: ${results_dir}/shadow_target_model_and_data
      training_json_config_paths: # Config json files used for tabddpm training on the trans table
        table_domain_file_path: ${base_data_dir}/trans_domain.json
        dataset_meta_file_path: ${base_data_dir}/dataset_meta.json
        training_config_path: ${base_data_dir}/trans.json  # if this is not present, it will be created by copying the example config
      fine_tuning_config:
        fine_tune_diffusion_iterations: 200000
        fine_tune_classifier_iterations: 20000
        pre_train_data_size: 60000
      number_of_points_to_synthesize: 20000 # Number of synthetic data samples to be generated by shadow models.

      final_shadow_models_path: [
        "${ensemble_attack.shadow_training.shadow_models_output_path}/initial_model_rmia_1/shadow_workspace/pre_trained_model/rmia_shadows.pkl",
        "${ensemble_attack.shadow_training.shadow_models_output_path}/initial_model_rmia_2/shadow_workspace/pre_trained_model/rmia_shadows.pkl",
        "${ensemble_attack.shadow_training.shadow_models_output_path}/shadow_model_rmia_third_set/shadow_workspace/trained_model/rmia_shadows_third_set.pkl",
      ]
      target_synthetic_data_path: ${ensemble_attack.shadow_training.target_model_output_path}/target_synthetic_data.csv

    # Metaclassifier settings
    metaclassifier:
      # Data types json file is used for xgboost model training.
      data_types_file_path: ${base_data_dir}/data_types.json
      model_type: "xgb"
      # Model training parameters
      num_optuna_trials: 100 # Original code: 100
      num_kfolds: 5
      use_gpu: false
      # Temporary. Might remove having an epoch parameter.
      epochs: 1
      meta_classifier_model_name: ${ensemble_attack.metaclassifier.model_type}_metaclassifier_model

    model_paths:
      metaclassifier_model_path: ${results_dir}/trained_models # Path where the trained metaclassifier model will be saved
