# Training example configuration
# Base data directory (can be overridden from command line)
base_data_dir: examples/gan/data
results_dir: examples/gan/results

ensemble_attack:
    random_seed: null  # Set this to a value if you want to set a random seed for reproducibility
    table_name: "trans"
    table_id_column_name: "trans_id"

    data_paths:
      processed_attack_data_path: ${base_data_dir}/ensemble_attack
      population_path: ${base_data_dir}/ensemble_attack

    shadow_training:
      model_name: ctgan
      model_config:  # Configurations specific for the CTGAN model
        training:
          epochs: 300
          verbose: True
        synthesizing:
          sample_size: 20000
      shadow_models_output_path: ${results_dir}/ensemble_attack/shadow_models
      training_json_config_paths: # Config json files used for tabddpm training on the trans table
        table_domain_file_path: ${base_data_dir}/trans_domain.json
        dataset_meta_file_path: ${base_data_dir}/dataset_meta.json
        training_config_path: ${base_data_dir}/trans.json  # if this is not present, it will be created by copying the example config
      fine_tuning_config:
        fine_tune_diffusion_iterations: 200000
        fine_tune_classifier_iterations: 20000
        pre_train_data_size: 60000
      number_of_points_to_synthesize: 20000 # Number of synthetic data samples to be generated by shadow models.
