"""Computes the Gower distance and membership signals between the challenge points
 and the synthetic data generated by the shadow models.
 Overall workflow and numerical decisions are taken with from CITADEL & UQAM team's attack implementation at
https://github.com/CRCHUM-CITADEL/ensemble-mia.
"""

from enum import Enum

import gower
import numpy as np
import pandas as pd


class Key(Enum):
    TRAINED_RESULTS = "trained_results"
    FINE_TUNED_RESULTS = "fine_tuned_results"


def get_rmia_gower(
    df_input: pd.DataFrame,
    model_data: dict[str, list],
    min_length: int,
    key: Key,
    categorical_column_names: list[str],
    id_column_name: str,
    random_seed: int = 42,
) -> list[np.ndarray]:
    """
    Computes the Gower distance and mean of the k-nearest neighbors (sorted by Gower distances) between the challenge
    points and the synthetic data generated by the shadow models.

    Args:
        df_input: The dataframe to generate features for (e.g., meta classifier train or test set), derived
            from the challenge dataset and processed in process_split_data.py.
        model_data: A dictionary with keys "fine_tuning_sets" and "fine_tuned_results".
                Fine_tuning_sets is a list of dataframes used to fine-tune the shadow models, and fine_tuned_results
                is a list of type TrainingResult containing model training information and generated synthetic data.
        min_length: Minimum length across all training data, fine tuning data, and synthetic data sizes. This length
            will be used for downsampling to ensure consistent Gower distance calculations.
        key: An instance of the Key Enum, either Key.TRAINED_RESULTS or Key.FINE_TUNED_RESULTS,
            depending on which set of shadow models to use.
        categorical_column_names: A list of categorical column names. We assume that all other columns are numerical.
        id_column_name: Name of the ID column.
        random_seed: Random seed for reproducibility.

    Returns:
        A list of numpy arrays, each representing the Gower distance matrix between the input dataframe and the
        synthetic data from a model. Each entry in the list corresponds to one of the synthetically generated
        datasets provided within `model_data`.

    """
    categorical_features = [column in categorical_column_names for column in df_input.columns]

    gower_matrices = []

    numerical_columns = [col for col in df_input.columns if col not in categorical_column_names]

    for i in range(len(model_data[key.value])):
        df_synthetic = model_data[key.value][i].synthetic_data.copy()

        # Convert numerical columns to float (otherwise error in the numpy divide)
        df_synthetic[numerical_columns] = df_synthetic[numerical_columns].astype(float)
        df_input[numerical_columns] = df_input[numerical_columns].astype(float)

        # Sample synthetic data points if there's too many
        if len(df_synthetic) > min_length:
            df_synthetic = df_synthetic.sample(n=min_length, random_state=random_seed)

        df_synthetic = df_synthetic.drop(columns=[id_column_name])

        gower_matrix = gower.gower_matrix(data_x=df_input, data_y=df_synthetic, cat_features=categorical_features)

        assert np.all((gower_matrix >= 0) & (gower_matrix <= 1)), "Distances are falling outside of range [0, 1]."

        gower_matrices.append(gower_matrix)

    return gower_matrices


def conditional_average(values: np.ndarray, condition_mask: np.ndarray) -> np.ndarray:
    """
    Calculate the conditional average of values based on a condition mask.
    This function computes the mean of the `values` array where the corresponding
    entries in the `condition_mask` are `True`. If no entries satisfy the condition
    for a particular record, the result will be `NaN` for that record.

    Args:
        values: A NumPy array containing the values to average.
        condition_mask (numpy.ndarray): A boolean NumPy array of the same shape as
            `values`, where `True` indicates the values to include in the average.

    Returns:
        An array of the same shape as the input, containing the conditional averages
        where the condition is met, or `NaN` where no values satisfy the condition.

    """
    mask_sum = condition_mask.sum(axis=0)
    return np.where(mask_sum > 0, np.sum(values * condition_mask, axis=0) / mask_sum, np.nan)


def calculate_rmia_signals(
    df_input: pd.DataFrame,
    attack_data_collection: list[dict[str, list]],
    target_data_collection: list[dict[str, list]],
    categorical_column_names: list[str],
    id_column_name: str,
    id_column_data: pd.Series,
    k: int = 5,
    random_seed: int = 42,
) -> pd.DataFrame:
    """
    Main orchestration function to compute Robust Membership Inference Attack (RMIA) signals
    with respect to shadow and target models.

    This function implements a data-based RMIA to determine the likelihood that a
    given data record was part of a target model's training set. The attack is
    data-based because it only uses synthetic data generated by the models, not the
    models themselves.

    The core idea is to compare a data record's similarity to two groups of synthetic data:
    1. Data generated by the 'target model' (the model we are simulating to attack).
    2. Data generated by several 'shadow models' (models trained on similar, but
       distinct, datasets).

    The intuition is that if a record was used to train the target model, the synthetic
    data it generates should be "closer" or more similar to that record than the
    synthetic data generated by the shadow models. This similarity is measured using
    Gower distance, which is suitable for datasets with mixed data types (both
    categorical and numerical).

    The final RMIA score is a ratio: (Similarity to Target) / (Mean Similarity to Shadows).
    A high RMIA score suggests that the record is disproportionately more similar to the
    target model's output, indicating a higher probability of being a training member.

    Args:
        df_input: The dataframe to generate features for (e.g., meta classifier train or test set), derived
            from the challenge dataset and processed in process_split_data.py.
        attack_data_collection: List of three elements. Each element contains training data of the shadow models
            and their generated synthetic data. The first two elements are dicts with keys "fine_tuning_sets" and
            "fine_tuned_results". The third element is a dict with keys "selected_sets" and "trained_results".
            fine_tuning_sets and selected_sets are lists of dataframes used to either train or fine-tune the
            shadow models. fine_tuned_results and trained_results are lists of type TrainingResult containing model
            training information and generated synthetic data.
            For more details, see the documentation of `train_three_sets_of_shadow_models` at
            attacks/ensemble/rmia/shadow_model_training.py.
        target_data_collection: List containing the target model and its synthetic data, used to compute RMIA signals.
        categorical_column_names: A list of categorical column names.
        id_column_name: Name of the ID column.
        id_column_data: The data in the ID column, used to ensure correct alignment of results.
        k: The number of nearest neighbors to consider when computing the final membership inference signals.
            A higher 'k' provides a more stable but less sensitive signal. Default is 5.
        random_seed: Random seed for reproducibility.

    Returns:
        A pandas DataFrame of shape (num_samples, 13) containing the following signals:
            - {id_column_name}: The ID column for result alignment.
            - signal_shadow_k_1: The smallest Gower distance from the input data to any shadow model's data
              (averaged across all shadow models). Lower is more similar.
            - signal_shadow_k_{k}: The mean of the 'k' smallest Gower distances from the
              input data to shadow models' data.
            - signal_shadows_in_k_1: Smallest distance from the input data for records known to be IN the
              shadow models' training sets (a baseline for member behavior).
            - signal_shadows_in_k_{k}: Mean of 'k' smallest distances from the input data for IN records.
            - signal_shadows_out_k_1: Smallest distance from the input data for records known to be OUT of
              the shadow models' training sets (a baseline for non-member behavior).
            - signal_shadows_out_k_{k}: Mean of 'k' smallest distances from the input data for OUT records.
            - signal_target_k_1: The smallest Gower distance from the input data to the target model's data.
            - signal_target_k_{k}: The mean of the 'k' smallest Gower distances from the input data to the
              target model's data.
            - rmia_k_1: The final RMIA score using the single nearest neighbor. A higher
              value indicates a stronger membership signal.
            - rmia_k_{k}: The final RMIA score using 'k' nearest neighbors.
            - rmia_out_k_1: RMIA score calibrated against the 'OUT' shadow signals,
              providing a more robust measure of membership.
            - rmia_out_k_{k}: RMIA score using 'k' neighbors, calibrated against the
              'OUT' shadow signals.
    """
    shadow_gower_list = []

    all_lengths = [
        [len(data.synthetic_data) for data in attack_data_collection[0]["fine_tuned_results"]],
        [len(data.synthetic_data) for data in attack_data_collection[1]["fine_tuned_results"]],
        [len(data.synthetic_data) for data in attack_data_collection[2]["trained_results"]],
        [len(data) for data in attack_data_collection[2]["selected_sets"]],
        [len(data) for data in attack_data_collection[0]["fine_tuning_sets"]],
        [len(data) for data in attack_data_collection[1]["fine_tuning_sets"]],
    ]

    min_length = min(min(group) for group in all_lengths)

    shadow_model_gower_0 = get_rmia_gower(
        df_input=df_input,
        model_data=attack_data_collection[0],
        min_length=min_length,
        key=Key.FINE_TUNED_RESULTS,
        categorical_column_names=categorical_column_names,
        id_column_name=id_column_name,
        random_seed=random_seed,
    )
    shadow_gower_list.append(np.array(shadow_model_gower_0))

    shadow_model_gower_1 = get_rmia_gower(
        df_input=df_input,
        model_data=attack_data_collection[1],
        min_length=min_length,
        key=Key.FINE_TUNED_RESULTS,
        categorical_column_names=categorical_column_names,
        id_column_name=id_column_name,
        random_seed=random_seed,
    )
    shadow_gower_list.append(np.array(shadow_model_gower_1))

    shadow_model_gower_2 = get_rmia_gower(
        df_input=df_input,
        model_data=attack_data_collection[2],
        min_length=min_length,
        key=Key.TRAINED_RESULTS,
        categorical_column_names=categorical_column_names,
        id_column_name=id_column_name,
        random_seed=random_seed,
    )
    shadow_gower_list.append(np.array(shadow_model_gower_2))

    gower_shadows = np.vstack(shadow_gower_list)

    # TODO: ideally remove hard-copied keys
    shadow_training_sets = (
        attack_data_collection[0]["fine_tuning_sets"]
        + attack_data_collection[1]["fine_tuning_sets"]
        + attack_data_collection[2]["selected_sets"]
    )

    # TODO: check key after we have the official target model
    target_model_gower = get_rmia_gower(
        df_input=df_input,
        model_data=target_data_collection[0],
        min_length=min_length,
        key=Key.FINE_TUNED_RESULTS,
        categorical_column_names=categorical_column_names,
        id_column_name=id_column_name,
    )

    # There is only one target model
    gower_target = target_model_gower[0]

    # Compute the signals based on the gower matrix wrt to the target synthetic data
    gower_target = np.sort(gower_target, axis=1)[:, :k]
    signal_target = np.mean(gower_target, axis=1)
    signal_target_k_1 = gower_target[:, 0]  # First element is the minimum

    # Process shadow model distances
    sorted_shadow_gower = np.sort(gower_shadows, axis=2)

    # For k nearest neighbors
    k_nearest_shadow_distances = sorted_shadow_gower[:, :, :k]
    mean_dist_shadow = np.mean(k_nearest_shadow_distances, axis=2)
    signal_shadows = np.mean(mean_dist_shadow, axis=0)

    # For single nearest neighbor (k=1)
    nearest_shadow_distances = sorted_shadow_gower[:, :, 0]
    signal_shadows_k_1 = np.mean(nearest_shadow_distances, axis=0)

    # Create a dataframe for the computed scores
    results_df = pd.DataFrame(
        {
            id_column_name: id_column_data.values,
            "signal_shadow_k_1": signal_shadows_k_1,
            f"signal_shadow_k_{k}": signal_shadows,
        }
    )

    # Create masks for records in/out of training sets
    mask_in_training = np.array(
        [
            [results_df[id_column_name][j] in shadow_training_sets[i] for j in range(len(results_df))]
            for i in range(len(shadow_training_sets))
        ]
    )

    mask_not_in_training = np.array(
        [
            [results_df[id_column_name][j] not in shadow_training_sets[i] for j in range(len(results_df))]
            for i in range(len(shadow_training_sets))
        ]
    )

    # Calculate signals based on membership status
    results_df["signal_shadows_in_k_1"] = conditional_average(nearest_shadow_distances, mask_in_training)
    results_df[f"signal_shadows_in_k_{k}"] = conditional_average(mean_dist_shadow, mask_in_training)
    results_df["signal_shadows_out_k_1"] = conditional_average(nearest_shadow_distances, mask_not_in_training)
    results_df[f"signal_shadows_out_k_{k}"] = conditional_average(mean_dist_shadow, mask_not_in_training)

    # Add target signals to results
    results_df["signal_target_k_1"] = signal_target_k_1
    results_df[f"signal_target_k_{k}"] = signal_target

    # Calculate RMIA scores (ratios of target to shadow signals)
    results_df["rmia_k_1"] = results_df["signal_target_k_1"] / results_df["signal_shadow_k_1"]
    results_df[f"rmia_k_{k}"] = results_df[f"signal_target_k_{k}"] / results_df[f"signal_shadow_k_{k}"]
    results_df["rmia_out_k_1"] = results_df["signal_target_k_1"] / results_df["signal_shadows_out_k_1"]
    results_df[f"rmia_out_k_{k}"] = results_df[f"signal_target_k_{k}"] / results_df[f"signal_shadows_out_k_{k}"]

    return results_df
