"""Computes the gower distance and membership signals between the challenge points
 and the synthetic data generated by the shadow models.
 Overall workflow and numerical decisions are taken with from CITADEL & UQAM team's attack implementation at
https://github.com/CRCHUM-CITADEL/ensemble-mia.
"""

import gower
import numpy as np
import pandas as pd


def get_rmia_gower(
    df_input: pd.DataFrame,
    model_data: dict,
    key: str,
    categorical_column_names: list[str],
    k: int,
    id_column_name: str,
) -> dict[str, list[np.ndarray]]:
    """
    Computes the Gower distance and mean of the k-nearest neighbors (sorted by Gower distances) between the challenge
    points and the synthetic data generated by the shadow models.

    Args:
        df_input: The dataframe to generate features for (e.g., meta classifier train or test set), derived
            from the challenge dataset and processed in process_split_data.py.
        model_data: A dictionary containing information about a diffusion model,
            specifically the data points it was trained or fine-tuned on and the synthetic data it generated.
        key: Either "trained_results" or "fine_tuned_results", depending on which set of shadow models to use.
        categorical_column_names: A list of categorical column names.
        k: Number of nearest neighbors to consider for the membership signal.
        id_column_name: Name of the ID column.

    Returns:
        A dictionary with two keys:
            "gower_matrix": A list of numpy arrays, each representing the Gower distance matrix
                between the input dataframe and the synthetic data from a model.
            "mean_distances": A list of numpy arrays, each containing the mean of the k smallest Gower distances
                for each row in the input dataframe with respect to a model's synthetic data.

    """
    categorical_features = [column in categorical_column_names for column in df_input.columns]

    gower_matrices = []
    mean_distances = []

    for i in range(len(model_data[key])):
        numerical_columns = [col for col in df_input.columns if col not in categorical_column_names]

        df_synthetic = model_data[key][i].synthetic_data.copy()

        # Convert numerical columns to float (otherwise error in the numpy divide)
        df_synthetic[numerical_columns] = df_synthetic[numerical_columns].astype(float)
        df_input[numerical_columns] = df_input[numerical_columns].astype(float)

        # Sample synthetic data points if there's too many
        # TODO: change this based on real shadow model training size
        # Sample = min(config.shadow_training.fine_tuning_config.pre_train_data_size, wherever the 2000 comes from)
        if len(df_synthetic) > 10:
            df_synthetic = df_synthetic.sample(n=10, random_state=42)

        df_synthetic = df_synthetic.drop(columns=[id_column_name])

        gower_matrix = gower.gower_matrix(data_x=df_input, data_y=df_synthetic, cat_features=categorical_features)

        if np.any((gower_matrix < 0) | (gower_matrix > 1)):
            print("Distances are falling outside of range [0, 1].")

        gower_matrices.append(gower_matrix)

        # TODO: check axis
        # Keep only the k smallest distances for each challenge point.
        # Original codebase says "first column is 0 for the within real/synth"
        distance = np.sort(gower_matrix, axis=1)[:, 0:k]
        mean_distance = np.mean(distance, axis=1)

        mean_distances.append(mean_distance)

    # TODO: potentially remove mean_distances
    return {"gower_matrix": gower_matrices, "mean_distances": mean_distances}


def calculate_rmia_signals(
    df_input: pd.DataFrame,
    attack_data_collection: list[dict],
    target_data_collection: list[dict],
    categorical_column_names: list[str],
    id_column_name: str,
    id_column_data: pd.Series,
    k: int = 5,
) -> pd.DataFrame:
    """
    Main orchestration function to compute Robust Membership Inference Attack (RMIA) signals
    with respect to shadow and target models.

    This function implements a data-based RMIA to determine the likelihood that a
    given data record was part of a target model's training set. The attack is
    data-based because it only uses synthetic data generated by the models, not the
    models themselves.

    The core idea is to compare a data record's similarity to two groups of synthetic data:
    1. Data generated by the 'target model' (the model we are simulating to attack).
    2. Data generated by several 'shadow models' (models trained on similar, but
       distinct, datasets).

    The intuition is that if a record was used to train the target model, the synthetic
    data it generates should be "closer" or more similar to that record than the
    synthetic data generated by the shadow models. This similarity is measured using
    Gower distance, which is suitable for datasets with mixed data types (both
    categorical and numerical).

    The final RMIA score is a ratio: (Similarity to Target) / (Similarity to Shadows).
    A high RMIA score suggests that the record is disproportionately more similar to the
    target model's output, indicating a higher probability of being a training member.


    Args:
        df_input: The dataframe to generate features for (e.g., meta classifier train or test set), derived
            from the challenge dataset and processed in process_split_data.py.
        attack_data_collection: List of trained shadow models and their synthetic data, used to compute RMIA signals.
        target_data_collection: List containing the target model and its synthetic data, used to compute RMIA signals.
        categorical_column_names: A list of categorical column names.
        id_column_name: Name of the ID column.
        id_column_data: The data in the ID column, used to ensure correct alignment of results.
        k: The number of nearest neighbors to consider when calculating the average
            Gower distance. A higher 'k' provides a more stable but less sensitive signal.
            Default is 5.

    Returns:
        A pandas DataFrame of shape (num_samples, 13) containing the following signals:
            - {id_column_name}: The ID column for result alignment.
            - signal_shadow_k_1: The smallest Gower distance to any shadow model's data
              (averaged across all shadow models). Lower is more similar.
            - signal_shadow_k_{k}: The mean of the 'k' smallest Gower distances to shadow
              models' data.
            - signal_shadows_in_k_1: Smallest distance for records known to be IN the
              shadow models' training sets (a baseline for member behavior).
            - signal_shadows_in_k_{k}: Mean of 'k' smallest distances for IN records.
            - signal_shadows_out_k_1: Smallest distance for records known to be OUT of
              the shadow models' training sets (a baseline for non-member behavior).
            - signal_shadows_out_k_{k}: Mean of 'k' smallest distances for OUT records.
            - signal_target_k_1: The smallest Gower distance to the target model's data.
            - signal_target_k_{k}: The mean of the 'k' smallest Gower distances to the
              target model's data.
            - rmia_k_1: The final RMIA score using the single nearest neighbor. A higher
              value indicates a stronger membership signal.
            - rmia_k_{k}: The final RMIA score using 'k' nearest neighbors.
            - rmia_out_k_1: RMIA score calibrated against the 'OUT' shadow signals,
              providing a more robust measure of membership.
            - rmia_out_k_{k}: RMIA score using 'k' neighbors, calibrated against the
              'OUT' shadow signals.
    """
    shadow_lists = []
    shadow_gower_list = []
    shadow_mean_dist_list = []
    gower_k_list = [10, 1, 5]
    for i in range(len(attack_data_collection)):
        attack_data = attack_data_collection[i]
        key = "fine_tuned_results"
        if i == 2:
            key = "trained_results"
        shadow_similarity_features = get_rmia_gower(
            df_input=df_input,
            model_data=attack_data,
            key=key,
            categorical_column_names=categorical_column_names,
            k=gower_k_list[i],
            id_column_name=id_column_name,
        )
        shadow_lists += attack_data[key]
        shadow_gower_list.append(np.array(shadow_similarity_features["gower_matrix"]))
        shadow_mean_dist_list.append(np.array(shadow_similarity_features["mean_distances"]))

    gower_shadows = np.vstack(shadow_gower_list)

    # TODO: ideally remove hard-copied keys
    shadow_lists = (
        attack_data_collection[0]["fine_tuning_sets"]
        + attack_data_collection[1]["fine_tuning_sets"]
        + attack_data_collection[2]["selected_sets"]
    )

    # TODO: check key after we have the official target model
    target_similarity_features = get_rmia_gower(
        df_input=df_input,
        model_data=target_data_collection[0],
        key="fine_tuned_results",
        categorical_column_names=categorical_column_names,
        k=10,
        id_column_name=id_column_name,
    )

    gower_target = target_similarity_features["gower_matrix"][0]

    # Compute the signals based on the gower matrix wrt to the target synthetic data
    gower_target = np.sort(gower_target, axis=1)[:, :k]
    signal_target = np.mean(gower_target, axis=1)
    signal_target_k_1 = np.min(gower_target, axis=1)

    # Compute the shadow signals for the value of k
    mean_dist_shadow = np.mean(np.sort(gower_shadows, axis=2)[:, :, :k], axis=2)
    signal_shadows = np.mean(mean_dist_shadow, axis=0)

    # Compute the shadow signals for k=1 (regardless of the set value of k above)
    min_dist_shadow = np.min(gower_shadows, axis=2)
    signal_shadows_k_1 = np.mean(min_dist_shadow, axis=0)

    # Create a dataframe for the computed scores
    signal_shadows = pd.DataFrame(signal_shadows, columns=["signal_shadow_k_" + str(k)])
    signal_shadows["signal_shadow_k_1"] = signal_shadows_k_1
    signal_shadows[id_column_name] = id_column_data.values

    # Create masks of shape (shadow models count, input data count) where True means that shadow_lists[i] contains
    # trans_id[j] for mask_in, and doesn't contain trans_id[j] for mask_out
    mask_in = np.array(
        [
            [signal_shadows[id_column_name][j] in shadow_lists[i] for j in range(len(signal_shadows))]
            for i in range(len(shadow_lists))
        ]
    )
    mask_out = np.array(
        [
            [signal_shadows[id_column_name][j] not in shadow_lists[i] for j in range(len(signal_shadows))]
            for i in range(len(shadow_lists))
        ]
    )

    signal_shadows["signal_shadows_in_k_1"] = np.where(
        mask_in.sum(axis=0) > 0, np.sum(min_dist_shadow * mask_in, axis=0) / mask_in.sum(axis=0), np.nan
    )
    signal_shadows["signal_shadows_in_k_" + str(k)] = np.where(
        mask_in.sum(axis=0) > 0, np.sum(mean_dist_shadow * mask_in, axis=0) / mask_in.sum(axis=0), np.nan
    )
    signal_shadows["signal_shadows_out_k_1"] = np.where(
        mask_out.sum(axis=0) > 0, np.sum(min_dist_shadow * mask_out, axis=0) / mask_out.sum(axis=0), np.nan
    )
    signal_shadows["signal_shadows_out_k_" + str(k)] = np.where(
        mask_out.sum(axis=0) > 0, np.sum(mean_dist_shadow * mask_out, axis=0) / mask_out.sum(axis=0), np.nan
    )

    # RMIA computation and selection of useful features
    signal_shadows["signal_target_k_1"] = signal_target_k_1
    signal_shadows["signal_target_k_" + str(k)] = signal_target
    signal_shadows["rmia_k_1"] = signal_shadows["signal_target_k_1"] / signal_shadows["signal_shadow_k_1"]
    signal_shadows["rmia_k_" + str(k)] = (
        signal_shadows["signal_target_k_" + str(k)] / signal_shadows["signal_shadow_k_" + str(k)]
    )
    signal_shadows["rmia_out_k_1"] = signal_shadows["signal_target_k_1"] / signal_shadows["signal_shadows_out_k_1"]
    signal_shadows["rmia_out_k_" + str(k)] = (
        signal_shadows["signal_target_k_" + str(k)] / signal_shadows["signal_shadows_out_k_" + str(k)]
    )

    return signal_shadows
