"""Computes the gower distance and membership signals between the challenge points
 and the synthetic data generated by the shadow models.
 Overall workflow and numerical decisions are taken with from CITADEL & UQAM team's attack implementation at
https://github.com/CRCHUM-CITADEL/ensemble-mia.
"""

import gower
import numpy as np
import pandas as pd


def get_rmia_gower(
    df_input: pd.DataFrame, model_data: dict, key: str, categorical_column_names: list[str], k: int
) -> dict[str, list[np.ndarray]]:
    """
    Computes the gower distance and membership signals between the challenge points
    and the synthetic data generated by the shadow models.

    Args:
        df_input: The dataframe to generate features for (e.g., meta classifier train or test set), derived
            from the challenge dataset and processed in process_split_data.py.
        model_data: A dictionary containing information about a diffusion model,
            specifically the data points it was trained or fine-tuned on and the synthetic data it generated.
        key: Either "trained_results" or "fine_tuned_results", depending on which set of shadow models to use.
        categorical_column_names: A list of categorical column names.
        k: Number of nearest neighbors to consider for the membership signal.

    Returns:
        A dictionary with two keys:
            "gower_matrix": A list of numpy arrays, each representing the Gower distance matrix
                between the input dataframe and the synthetic data from a model.
            "mean_distances": A list of numpy arrays, each containing the mean of the k smallest Gower distances
                for each row in the input dataframe with respect to a model's synthetic data.

    """
    categorical_features = [column in categorical_column_names for column in df_input.columns]

    gower_matrices = []
    mean_distances = []

    for i in range(len(model_data[key])):
        df_synthetic = model_data[key][i]["synth_data"]

        # Convert numerical columns to float (otherwise error in the numpy divide)
        numerical_columns = [col for col in df_synthetic.columns if col not in categorical_column_names]

        df_synthetic[numerical_columns] = df_synthetic[numerical_columns].astype(float)
        df_input[numerical_columns] = df_input[numerical_columns].astype(float)

        df_synthetic_sampled = df_synthetic.sample(n=20000, random_state=42)

        gower_matrix = gower.gower_matrix(
            data_x=df_input, data_y=df_synthetic_sampled, cat_features=categorical_features
        )

        if np.any((gower_matrix < 0) | (gower_matrix > 1)):
            print("Distances are falling outside of range [0, 1].")

        gower_matrices.append(gower_matrix)

        # TODO: check axis
        # Keep only the k smallest distances for each challenge point.
        # Original codebase says "first column is 0 for the within real/synth"
        distance = np.sort(gower_matrix, axis=1)[:, 0:k]
        mean_distance = np.mean(distance, axis=1)

        mean_distances.append(mean_distance)

    # TODO: potentially remove mean_distances

    return {"gower_matrix": gower_matrices, "mean_distances": mean_distances}


def calculate_rmia_signals(
    df_input: pd.DataFrame,
    attack_data_collection: list[dict],
    target_data_collection: list[dict],
    categorical_column_names: list[str],
) -> pd.DataFrame:
    """
    Main orchestration function to compute RMIA signals for the input dataframe with respect to both shadow and target models.

    Args:
        df_input: The dataframe to generate features for (e.g., meta classifier train or test set), derived
            from the challenge dataset and processed in process_split_data.py.
        attack_data_collection: List of trained shadow models and their synthetic data, used to compute RMIA signals.
        target_data_collection: List containing the target model and its synthetic data, used to compute RMIA signals.
        categorical_column_names: A list of categorical column names.   

    #TODO
    Returns:
        A dataframe containing RMIA signals, with shape (num_samples, __).
        The __ features include:
            

        
    """
    shadow_gower_list = []
    shadow_mean_dist_list = []
    k_list = [10, 1, 5]
    for i in range(len(attack_data_collection)):
        attack_data = attack_data_collection[i]
        # TODO: make sure df_input has ids
        key = "fine_tuned_results"
        if i == 2:
            key = "trained_results"
        shadow_similarity_features = get_rmia_gower(
            df_input=df_input, model_data=attack_data, key=key, categorical_column_names=categorical_column_names, k=k_list[i]
        )
        shadow_gower_list.append(np.array(shadow_similarity_features["gower_matrix"]))
        shadow_mean_dist_list.append(np.array(shadow_similarity_features["mean_distances"]))

    gower_shadows = np.vstack(shadow_gower_list)

    # TODO: make sure df_input has ids
    # TODO: check key
    
    target_similarity_features = get_rmia_gower(
        df_input=df_input,
        model_data=target_data_collection[0],
        key="fine_tuned_results",
        categorical_column_names=categorical_column_names,
        k=10,
    )

    # Create an empty dataframe to store the RMIA signals
    rmia_signals = pd.DataFrame()
    return rmia_signals
