from collections.abc import Callable
from enum import Enum
from typing import Any

import numpy as np
from torch import nn


# TODO: Temporary, will switch to classes later
Configs = dict[str, Any]
Tables = dict[str, dict[str, Any]]
RelationOrder = list[tuple[str, str]]
GroupLengthsProbDicts = dict[tuple[str, str], dict[int, dict[int, float]]]
ArrayDict = dict[str, np.ndarray]
ModuleType = str | Callable[..., nn.Module]


class ClusteringMethod(Enum):
    """Possioble clustering methods for multi-table training."""

    KMEANS = "kmeans"
    GMM = "gmm"
    KMEANS_AND_GMM = "kmeans_and_gmm"
    VARIATIONAL = "variational"


class IsTargetCondioned(Enum):
    """
    The condition on the y column.

    IsTargetCondioned.CONCAT: y is concatenated to X, the model learn a joint distribution of (y, X)
    IsTargetCondioned.EMBEDDING: y is not concatenated to X. During computations, y is embedded
        and added to the latent vector of X
    IsTargetCondioned.NONE: y column is completely ignored

    How does IsTargetCondioned affect the generation of y?
    IsTargetCondioned:
        IsTargetCondioned.CONCAT: the model synthesizes (y, X) directly, so y is just the first column
        IsTargetCondioned.EMBEDDING: y is first sampled using empirical distribution of y. The model only
            synthesizes X. When returning the generated data, we return the generated X
            and the sampled y. (y is sampled from empirical distribution, instead of being
            generated by the model)
            Note that in this way, y is still not independent of X, because the model has been
            adding the embedding of y to the latent vector of X during computations.
        IsTargetCondioned.NONE:
            y is synthesized using y's empirical distribution. X is generated by the model.
            In this case, y is completely independent of X.
    """

    CONCAT = "concat"
    EMBEDDING = "embedding"
    NONE = "none"


class ReductionMethod(Enum):
    """Possible methods of reduction."""

    MEAN = "mean"
    SUM = "sum"
    NONE = "none"


class Normalization(Enum):
    """Possible types of normalization."""

    STANDARD = "standard"
    QUANTILE = "quantile"
    MINMAX = "minmax"


class NumericalNaNPolicy(Enum):
    """Possible policies for dealng with NaNs in numerical data."""

    DROP_ROWS = "drop-rows"
    MEAN = "mean"


class CategoricalNaNPolicy(Enum):
    """Possible policies for dealng with NaNs in categorical data."""

    MOST_FREQUENT = "most_frequent"


class CategoricalEncoding(Enum):
    """Possible types of encoding for categorical data."""

    ONE_HOT = "one-hot"
    COUNTER = "counter"
    ORDINAL = "ordinal"


class TargetPolicy(Enum):
    """Possible types of policy for the model target."""

    DEFAULT = "default"


class TargetType(Enum):
    """Possible types of model target."""

    FLOAT = "float"
    LONG = "long"
