from enum import Enum
from typing import Any

import numpy as np


# TODO: Temporary, will switch to classes later
Configs = dict[str, Any]
Tables = dict[str, dict[str, Any]]
Relation = tuple[str, str]
RelationOrder = list[Relation]
GroupLengthProbDict = dict[int, dict[int, float]]
GroupLengthsProbDicts = dict[Relation, GroupLengthProbDict]
ArrayDict = dict[str, np.ndarray]


class ClusteringMethod(Enum):
    """Possible clustering methods for multi-table training."""

    KMEANS = "kmeans"
    GMM = "gmm"
    KMEANS_AND_GMM = "kmeans_and_gmm"
    VARIATIONAL = "variational"


class IsTargetConditioned(Enum):
    """
    The condition on the y column.

    IsTargetConditioned.CONCAT: y is concatenated to X, the model learn a joint distribution of (y, X)
    IsTargetConditioned.EMBEDDING: y is not concatenated to X. During computations, y is embedded
        and added to the latent vector of X
    IsTargetConditioned.NONE: y column is completely ignored

    How does IsTargetConditioned affect the generation of y?
    IsTargetConditioned:
        IsTargetConditioned.CONCAT: the model synthesizes (y, X) directly, so y is just the first column
        IsTargetConditioned.EMBEDDING: y is first sampled using empirical distribution of y. The model only
            synthesizes X. When returning the generated data, we return the generated X
            and the sampled y. (y is sampled from empirical distribution, instead of being
            generated by the model)
            Note that in this way, y is still not independent of X, because the model has been
            adding the embedding of y to the latent vector of X during computations.
        IsTargetConditioned.NONE:
            y is synthesized using y's empirical distribution. X is generated by the model.
            In this case, y is completely independent of X.
    """

    CONCAT = "concat"
    EMBEDDING = "embedding"
    NONE = "none"


class ReductionMethod(Enum):
    """Possible methods of reduction."""

    MEAN = "mean"
    SUM = "sum"
    NONE = "none"


class Normalization(Enum):
    """Possible types of normalization."""

    STANDARD = "standard"
    QUANTILE = "quantile"
    MINMAX = "minmax"


class NumericalNaNPolicy(Enum):
    """Possible policies for dealng with NaNs in numerical data."""

    DROP_ROWS = "drop-rows"
    MEAN = "mean"


class CategoricalNaNPolicy(Enum):
    """Possible policies for dealng with NaNs in categorical data."""

    MOST_FREQUENT = "most_frequent"


class CategoricalEncoding(Enum):
    """Possible types of encoding for categorical data."""

    ONE_HOT = "one-hot"
    COUNTER = "counter"
    ORDINAL = "ordinal"


class TargetPolicy(Enum):
    """Possible types of policy for the model target."""

    DEFAULT = "default"


class TargetType(Enum):
    """Possible types of model target."""

    FLOAT = "float"
    LONG = "long"


class DataAndKeyNormalizationType(Enum):
    """Possible types of normalization for data and primary keys when clustering."""

    MINMAX = "minmax"
    QUANTILE = "quantile"


class ModuleType(Enum):
    """Possible types of modules for the MLP or ResNet models."""

    REGLU = "ReGLU"
    GEGLU = "GEGLU"
    RELU = "ReLU"
    BATCH_NORM_1D = "BatchNorm1d"
