# Ensemble experiment configuration for diabetes dataset, 10k
# This config can be used to run both the Ensemble attack training (``run_attack.py``) and testing phases (``test_attack_model.py``).
base_experiment_dir: /projects/midst-experiments/ensemble_attack/diabetes_experiments/10k_permute/run2 # Processed data, and experiment artifacts will be stored under this directory.
base_data_config_dir: examples/ensemble_attack/diabetes/data_configs # Training and data type configs are saved under this directory.

# Training Pipeline Control
pipeline:
  run_data_processing: True # Set this to false if you have already saved the processed data
  run_shadow_model_training: True # Set this to false if shadow models are already trained and saved
  run_metaclassifier_training: True

target_model: # This is only used for testing the attack on a real target model.
  target_model_directory: /projects/midst-experiments/diabetes_experiments_newer/whitebox_single_table_DI_1/50_percent_noise_permute/try_again_12/
  target_model_id: 8  # Will be overridden per SLURM array task
  target_model_name: tabddpm_${target_model.target_model_id}
  target_synthetic_data_path: ${target_model.target_model_directory}/${target_model.target_model_name}/models_S4_try_again_12/${target_model.target_model_name}_synthesizing_S4_try_again_12/trans/_final/trans_synthetic_clean.csv

  challenge_directory: /projects/midst-experiments/ensemble_attack/diabetes_experiments/10k_permute/1k_challange_points_dir # Contains 1k challenge points
  challenge_data_path: ${target_model.challenge_directory}/${target_model.target_model_name}/challenge_with_id.csv
  challenge_label_path: ${target_model.challenge_directory}/${target_model.target_model_name}/challenge_label.csv

  target_shadow_models_output_path: ${base_experiment_dir}/test_all_targets # Sub-directory to store test shadows and results
  attack_probabilities_result_path: ${target_model.target_shadow_models_output_path}/test_probabilities/attack_model_${target_model.target_model_id}_proba
  attack_rmia_shadow_training_data_choice: "combined" # Options: "combined", "only_challenge", "only_train". This determines which data to use for training RMIA attack model in testing phase.
  # See select_challenge_data_for_training()'s docstring for more details.


# Data paths
data_paths:
  processed_base_data_dir: ${base_experiment_dir} # To save new processed data for training, or read from previously collected and processed data (testing phase).
  population_path: ${data_paths.processed_base_data_dir}/population_data  # Path where the collected population data will be stored (output/input)
  processed_attack_data_path: ${data_paths.processed_base_data_dir}/attack_data # Path where the processed attack real train and evaluation data is stored (output/input)
  attack_evaluation_result_path: ${base_experiment_dir}/evaluation_results # Path where the attack (train phase) evaluation results will be stored (output)


model_paths:
  metaclassifier_model_path: ${base_experiment_dir}/trained_models # Path where the trained metaclassifier model will be saved


# Dataset specific information used for processing in this example
data_processing_config:
  dataset_path: /projects/midst-experiments/diabetes_experiments_newer/whitebox_single_table_DI_1/ # Used to collect the data (input)
  # The following directories should exist and contain `tabddpm_{i} for i in folder_ranges`:
  # population data: midst_data_path/population_attack_data_types_to_collect/population_splits
  # challenge data: midst_data_path/challenge_attack_data_types_to_collect/challenge_splits
  population_attack_data_types_to_collect:
        [
          "50_percent_noise_permute", # These mean nothing, just for the sake of pointing to the correct directory.
        ]
  challenge_attack_data_types_to_collect: 
        [
          "50_percent_noise_permute",
        ]
  population_splits: ["try_again_12"]  # Data splits to be collected for population data
  challenge_splits: ["try_again_12"]  # Data splits to be collected for challenge points
  test_challenge_data_path_for_training: ${target_model.challenge_directory} # We should also provide challenge points (test data points) during training of RMIA shadow models. 
  original_population_data_path: null

  # The column name in the data to be used for stratified splitting.
  column_to_stratify: "race_categorical"  # Attention: This value is not documented in the original codebase.
  folder_ranges: # Specify folder ranges for any of the mentioned splits.
    try_again_12: [[1, 8]] # Folders to be used for train data collection in the experiments
    final: [[8, 11]]
  # File names in MIDST data directories.
  single_table_train_data_file_name: "train_with_id.csv"
  multi_table_train_data_file_name: "trans.csv"
  challenge_data_file_name: "challenge_with_id.csv"
  population_sample_size: 20000 # Population size is the total data that your attack has access to.
  # In experiments, this is sampled out of all the collected training data in case the available data
  # is more than this number. Note that, half of this data is actually used for training, the other half
  # is used for evaluation. For example, with 40k population size, only 20k is used for training the attack model.
  # TODO: make sure to consider this in experiments.

# Training and data settings for shadow models (temporary, numbers subject to change)
shadow_training:
  # Data Config files path used for training a TabDDPM model
  training_json_config_paths: # Config json files used for tabddpm training on the trans table
    table_domain_file_path: ${base_data_config_dir}/trans_domain.json
    dataset_meta_file_path: ${base_data_config_dir}/dataset_meta.json
    tabddpm_training_config_path: ${base_data_config_dir}/trans.json
  # Model training artifacts are saved under shadow_models_data_path/workspace_name/exp_name
  # Also, training configs for each shadow model are created under shadow_models_data_path.
  shadow_models_output_path: ${base_experiment_dir}/shadow_models_and_data
  target_model_output_path: ${base_experiment_dir}/shadow_target_model_and_data
  # Paths to final shadow models used for metaclassifier training (relative to shadow_models_output_path)
  # These paths are a result of running the shadow model training pipeline, specifically the
  # train_three_sets_of_shadow_models in shadow_model_training.py
  # Each .pkl file contains the training data, trained model and training results for all shadow models in a list.
  final_shadow_models_path: [
          "${shadow_training.shadow_models_output_path}/initial_model_rmia_1/shadow_workspace/pre_trained_model/rmia_shadows.pkl",
          "${shadow_training.shadow_models_output_path}/initial_model_rmia_2/shadow_workspace/pre_trained_model/rmia_shadows.pkl",
          "${shadow_training.shadow_models_output_path}/shadow_model_rmia_third_set/shadow_workspace/trained_model/rmia_shadows_third_set.pkl",
      ]
  target_synthetic_data_path: ${shadow_training.target_model_output_path}/target_synthetic_data.csv
  # Path to final shadow target's synthetic data (relative to target_model_output_path)
  fine_tuning_config:
    fine_tune_diffusion_iterations: 200000 # Original code: 200000
    fine_tune_classifier_iterations: 20000 # Original code: 20000
    pre_train_data_size: 50000 # Default: 50000
  number_of_points_to_synthesize: 10000 # Number of synthetic data samples to be generated by shadow models.
  # Original code: 20000


# Metaclassifier settings
metaclassifier:
  # Data types json file is used for xgboost model training.
  data_types_file_path: ${base_data_config_dir}/data_types.json
  model_type: "xgb"
  # Model training parameters
  num_optuna_trials: 100 # Original code: 100
  num_kfolds: 5
  use_gpu: false
  # Temporary. Might remove having an epoch parameter.
  epochs: 1
  meta_classifier_model_name: ${metaclassifier.model_type}_metaclassifier_model

attack_success_computation:
  target_ids_to_test: [8, 9, 10] # List of target model IDs to compute the attack success for.

# General settings
random_seed: 43 # Set to null for no seed, or an integer for a fixed seed
