name: code checks
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - '**.py'
      - uv.lock
      - pyproject.toml
      - '**.ipynb'
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - '**.py'
      - uv.lock
      - pyproject.toml
      - '**.ipynb'

jobs:
  run-code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4
        with:
          # Install a specific version of uv.
          version: "0.5.21"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install dependencies and check code
        run: |
          source .venv/bin/activate
          pre-commit run --all-files

      - name: pip-audit (gh-action-pip-audit)
        uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266
        with:
          virtual-environment: .venv/
          # GHSA-887c-mr87-cxwp torch vulnerability without a fix yet
          # PYSEC-2025-41, PYSEC-2024-259: These ignores are temporary. Synthcity needs python below or at 2.4 and
          # these vulnerabilities exist until 2.5. However, we'll be removing the Synthcity dependency in follow up.
          # So we'll be able to upgrade torch and drop these there.
          ignore-vulns: |
            GHSA-887c-mr87-cxwp
            GHSA-3749-ghw9-m3mg
            PYSEC-2025-41
            PYSEC-2024-259
